syntax = "proto3";

package hegadb.protocol;

import "common.proto";

message EncryptedParameter {
  uint32 index = 1;
  bytes ciphertext = 2;
}

message ColumnRef {
  string table = 1;
  string column = 2;
}

message ParameterRef {
  uint32 parameter_index = 1;
}

message Wildcard {}

enum ComparisonOp {
  COMPARISON_OP_UNSPECIFIED = 0;
  COMPARISON_OP_EQ = 1;
  COMPARISON_OP_NEQ = 2;
  COMPARISON_OP_LT = 3;
  COMPARISON_OP_GT = 4;
  COMPARISON_OP_LTE = 5;
  COMPARISON_OP_GTE = 6;
}

enum LogicalOp {
  LOGICAL_OP_UNSPECIFIED = 0;
  LOGICAL_OP_AND = 1;
  LOGICAL_OP_OR = 2;
}

message ComparisonExpr {
  Expression left = 1;
  ComparisonOp operator = 2;
  Expression right = 3;
}

message LogicalExpr {
  Expression left = 1;
  LogicalOp operator = 2;
  Expression right = 3;
}

message NotExpr {
  Expression child = 1;
}

message Expression {
  oneof expr_type {
    ColumnRef column_ref = 1;
    ParameterRef parameter_ref = 2;
    Wildcard wildcard = 3;
    LogicalExpr logical_expr = 4;
    ComparisonExpr comparison_expr = 5;
    NotExpr not_expr = 6;
  }
}

message TableRef {
  string table = 1;
}

message SelectStatement {
  repeated Expression projections = 1;
  TableRef from_table = 2;
  Expression where = 3;
}

message Statement {
  oneof statement {
    SelectStatement select_statement = 1;
  }
}

message ExecuteQuery {
  ProtocolVersion protocol_version = 1;
  RequestId request_id = 2;
  Statement statement = 3;
  repeated EncryptedParameter parameters = 4;
}

message QueryResponse {
  ProtocolVersion protocol_version = 1;
  RequestId request_id = 2;
  Status status = 3;
}
